apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ instance_name }}-demo
  labels:
    app: {{ instance_name }}-demo
spec:
  selector:
    matchLabels:
      app: {{ instance_name }}-demo
  template:
    metadata:
      name: {{ instance_name }}-demo
      labels:
        app: {{ instance_name }}-demo
    spec:
      containers:
      - name: {{ instance_name }}-demo
        image: {{ spring-boot-demo-docker.image }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: prometheus
          containerPort: 9090
          protocol: TCP
        resources:
          limits:
            cpu: "2" # cpu 限制
            memory: "2048Mi" # 内存限制
          requests:
            cpu: "2" # cpu 预留（与限制值一致）
            memory: "2048Mi" # 内存预留（与限制值一致）
---
apiVersion: v1
kind: Service
metadata:
  name: {{ instance_name }}-demo
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    app: {{ instance_name }}-demo
